name: Update WakaTime Stats

on:
  schedule:
    - cron: '0 * * * *'  # 매 시간마다 실행
  push:
    branches:
      - main  # 메인 브랜치에 푸시할 때 실행

jobs:
  update-wakatime:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Python 버전 지정

      - name: Install requests module
        run: pip install requests

      - name: Update WakaTime Stats
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        run: |
          curl -s "https://wakatime.com/api/v1/users/current/stats/last_7_days?api_key=${WAKATIME_API_KEY}" > wakatime-stats.json
          echo -e "## WakaTime Stats\n\n![WakaTime stats](https://github-readme-stats.vercel.app/api/wakatime?username=${{ secrets.WAKATIME_USERNAME }})" > README.md
          git add README.md

      - name: Commit and Push if changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git diff --quiet || git commit -m "Update WakaTime stats" && git push origin HEAD
